<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Features\Orders\Create\" />
    <Folder Include="Features\Orders\Delete\" />
    <Folder Include="Features\Orders\Update\" />
  </ItemGroup>

</Project>
